<div class="page-header">
  <h1>Welcome to <?php echo CHtml::encode(Yii::app()->name)?>
    <small><h3>An Interactive Plotter for Energy Spectrum of Stochastic Gravitational Wave Backgrounds from Various Theoretical Models</h3>
</small></h1>
</div>


<div class="well">The pages are currently maintained by
		<a href="mailto:mandic@physics.umn.edu">Professor Vuk Mandic (University of Minnesota)</a>, 
		<a href="mailto:regimbau@oca.eu">Tania Regimbau(Observatoire de la Cote d’Azur.)</a> and  
		<a href="mailto:wuxxx528@umn.edu">Chengjian Wu (University of Minnesota)</a>.
		If you decide to use a plot generated by this site please consider giving this site, and us, a credit. (You can remove the site address label from the plots with the check box at the bottom of the page.)
<ul>
			<li> Please select each model and the relevent values for the parameters you wish to plot using the form below. When you have finished the selection press "Generate Plot" once and then wait for the new results page to appear. The new page can take some time to appear depending on the server load. </li>
			<li> Please note that you can use the browser "Back" button to return to this page, and your data/color selections from your previous plot will be remembered.</li>
</ul>  
</div>
<?php
/* @var $this PlotterController */

// $this->breadcrumbs=array('Plotter');
?>

<?php /** @var BootActiveForm $form */
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'verticalForm',
    'htmlOptions'=>array('class'=>'well'),
)); ?>
 
  <!-- <form method="post" action="dialing.php" id="wrapper_Data_Form" onsubmit="popup(this)"> -->
	<table id="wrapper_Data_Bounds">
		<caption><b>PLOT SPECIFICATIONS</b></caption>
		
      	<tr>
			<th align="left">Set by 
				<select name="axis_auto">			
				<option selected="selected" value="1">auto</option>
				<option value="0">manually</option></select>
			</th>
			<th align="center"> Min </th>
			<th align="center"> Max </th>		
		<!--<th ALIGN=CENTER WIDTH="500" HEIGHT="17" BORDER="0"> </th>-->
		</tr>

				<tr>
			<td align="left">X-axis (Frequency):</td>
			<td class="central"><input name="xmin" value="1" type="text" /></td>
			<td class="central"><input name="xmax" value="1000" type="text" /></td>
		</tr>

		<tr>
			<td align="left">Y-axis (Energy Spectrum):</td>
			<td class="central"><input name="ymin" value="1e-18" type="text" /></td>
			<td class="central"><input name="ymax" value="1e-6" type="text" /></td>
		</tr>

		<tr>
			<td align="left">Number of Points <input name="numpoints" value="500" type="text" />:</td>
			<td class="central">2</td>
			<td class="central">As long as you want to wait</td>
		</tr>

		<tr>
			<td align="left">Star Formation Rate</td>
			<td colspan="2" class+"central">
				<select name="sfrate">
				<?php // include("html/sfm.php"); ?>
			</td>		
		</tr>
	</table><hr />
	<table id="wrapper_Data_models">
	<thead>

	<tr><th colspan="4">
	  <input value="Generate Plot" type="submit" />[Please note there may be up to 30 second wait for plots]<hr />
	</th></tr>

		<tr>
			<th class="wrapper_Data_col1">GW Model Name</th>
			<th class="wrapper_Data_col2">Parameters </th>
			<th class="wrapper_Data_col3">Plot Specify</th>
			<th class="wrapper_Data_col4">Introduction </th>
		</tr>
	</thead>	
	
	<tbody>			
	<tr><th colspan="4"><hr /></th></tr>
  <?php foreach ($modeltypes as $modeltype) {
    echo '<tr><th colspan="4">'.$modeltype->name.'<br /><hr /></th></tr>';
    $models=Models::model()->findAllByAttributes(array('type_id' => $modeltype->id));
    foreach ($models as $i=>$model) {
      echo $this->renderPartial('_model', array('model'=>$model, 'i'=>$i));
    };
  } ?>
  </tbody>
	</table>

	<div> 
		<br />
		<input name="no_idtext" value="1" type="checkbox" />Check here to remove site address from main plot. <br />
		<input name="no_name" value="1" type="checkbox" />Check here to remove site names from main plot.
	</div>

	<p><input value="Generate Plot" type="submit" />[Please note there may be up to 30 second wait for plots]</p>

<?php $this->endWidget(); ?>
