INSERT INTO tbl_entity (name, content)  VALUES ('site_inform', 'The pages are currently maintained by [Professor Vuk Mandic (University of Minnesota)](mailto:mandic@physics.umn.edu), [Tania Regimbau(Observatoire de la Cote d’Azur.)](mailto:regimbau@oca.eu) and [Chengjian Wu (University of Minnesota)](mailto:wuxxx528@umn.edu).

If you decide to use a plot generated by this site please consider giving this site, and us, a credit. (You can remove the site address label from the plots with the check box at the bottom of the page.)

* Please select each model and the relevent values for the parameters you wish to plot using the form below. When you have finished the selection press "Generate Plot" once and then wait for the new results page to appear. The new page can take some time to appear depending on the server load.
* Please note that you can use the browser "Back" button to return to this page, and your data/color selections from your previous plot will be remembered.');